### ISSUE TITLE
mouseover info

### ISSUE THREAD

**Issue by Tealk** [PRATAP-KUMAR/rounded-system-menu-buttons#2]
would it be possible to insert a mouseover for information which button has which function?
At the beginning some icons were not clear for me

**Comment by pratap-panabaka** [comment]
I too thought like you..
I will try to make it in few days.

**Comment by iadegesso** [comment]
It will be very useful! :D 

Thanks,

Iade

**Comment by pratap-panabaka** [comment]
@iadegesso thanks for your feedback.. I am working on it.. possibly in couple of days I am trying to implement it.

**Comment by pratap-panabaka** [comment]
@iadegesso @Tealk Hi,
Have uploaded the extension to gnome-extensions website for review.. Once it is approved.. the hover on buttons will show the labels. This is done for version gnome-shell version 41 only. for 3.36 and 3.38 I am facing some issues. Will do it for them later.
I hope you are using the latest gnome-shell versions.

**Comment by Tealk** [comment]
looks good, thank you

**Comment by pratap-panabaka** [comment]
@iadegesso Hi,

> iadegesso
> 2021-12-28 update makes my GNOME environment leading to a crash

when it crashed what is your gnome-shell version?
if your shell version does not match extensions version then there is possibility of crash.

any how I have find out the reason for crash if your gnome-shell is 3.36 or 3.38 and used extensions version for 41.
Have uploaded the extension to gnome-extensions org website, Once it is approved 3.36 and 3.38 will also have mouseover info.

Thanks!!!

![1](https://user-images.githubusercontent.com/40719899/147759965-7950f7d6-89c3-453c-9267-fdd43ec139ad.gif)

**Comment by iadegesso** [comment]
> when it crashed what is your gnome-shell version?
> if your shell version does not match extensions version then there is possibility of crash.

I'm on GNOME 41, and it crashed in GNOME 41 after updating from the GNOME Extensions web site.


Iade

**Comment by pratap-panabaka** [comment]
Hi, thanks for reply. Did extension version 9 has the same issue? Did you try extension version 9. If yes do you have screen orientation?

**Comment by iadegesso** [comment]
I cannot help you... now, I installed version 10 and it works fine!


Iade

**Comment by pratap-panabaka** [comment]
Hi lade, Thanks for your reply. The date you mentioned, that version was for gnome shell 3.36 and 3.38 where as your gnome-shell version is 41 that could be the reason for crash. The higher version on 28th date is for 3.36 and 3.38. Did you install it manually or system notified you that latest version is available on the day of crash? Any how thanks for your feedback about version 10 of the extension.

**Comment by iadegesso** [comment]
Yes I updated the extension because the system showed me a message about a new update... I updated the extension through the GNOME Extensions web page, and after it updated my GNOME Shell crashed.

I uninstalled the extension and I manually reinstalled it when you told me that version 10 was released.


Iade
