### ISSUE TITLE
Settings screen crashes on gnome shell 40.5

### ISSUE THREAD

**Issue by whoozy82** [PRATAP-KUMAR/rounded-system-menu-buttons#3]
The settings of extension roundedSystemMenuButtons@pratap.fastmail.fm had an error:
```
Error: No property border_width on GtkBox
```

Stack trace:
```
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
PrefsWidget@/home/kay/.local/share/gnome-shell/extensions/roundedSystemMenuButtons@pratap.fastmail.fm/prefs.js:24:23
buildPrefsWidget@/home/kay/.local/share/gnome-shell/extensions/roundedSystemMenuButtons@pratap.fastmail.fm/prefs.js:14:18
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by pratap-panabaka** [comment]
Hi.. are you using extension version 3 or 4?

**Comment by whoozy82** [comment]
It looks like gnome version 41 is mapped to extension version 3 and gnome 3.38 is mapped to version 4.

https://extensions.gnome.org/extension/4693/rounded-system-menu-buttons/

So I assume that I am on extension version 3. How can I find out more correct?

**Comment by whoozy82** [comment]
I just tried out both - and both are throwing the error when loading the settings.
But: version 4 brings out red icons in the menu, whereas version 3 brings correct theme fitting icons.

**Comment by pratap-panabaka** [comment]
Hi, run `gnome-shell --version` command and the version it gives is the gnome-shell version, once you knew your gnome-shell version, you need to choose shell version from gnome-extensions website. As you mentioned your shell version is 40.5, this extension version is not tested for shell version 40. I am on version 41 when tested this. I will have to install version 40 and test it.
