### ISSUE TITLE
Blue buttons since last update

### ISSUE THREAD

**Issue by Tealk** [PRATAP-KUMAR/rounded-system-menu-buttons#4]
Since the last update the buttons are blue and the mouseover is poison green

![Bildschirmfoto vom 2022-01-26 20-50-46](https://user-images.githubusercontent.com/12276250/151236376-cd550f91-b6fb-481e-aee3-fb60121bff3a.jpg)

**Comment by pratap-panabaka** [comment]
Yes it is made intentionally to cover all other OS which uses GNOME. Go to settings page of extension copy the last line and run it in terminal then you can set what ever color you wish.

**Comment by Tealk** [comment]
where can you find out the original color code of the menu?

**Comment by pratap-panabaka** [comment]
/* Add your custom extension styling here */

.rounded-menu-buttons {
background-color: transparent;
}

.rounded-menu-buttons:hover, .rounded-menu-buttons:focus {
background-color: rgba(0, 0, 236, 0.5);
}

.rounded-menu-buttons:active {
background-color: #215d9c;
}

**Comment by Tealk** [comment]
I have set that now and it looks nice and subtle.

```
.rounded-menu-buttons {
  background-color: transparent;
}

.rounded-menu-buttons:hover, .rounded-menu-buttons:focus {
  background-color: rgba(255, 255, 255, 0.3);
}

.rounded-menu-buttons:active {
  background-color: rgba(255, 0, 0, 0);
}
```

**Comment by pratap-panabaka** [comment]
You are great @Tealk
