### ISSUE TITLE
Setting Button Missing on Pop!_OS 22.04 with GNOME 42.1

### ISSUE THREAD

**Issue by jfftck** [PRATAP-KUMAR/rounded-system-menu-buttons#5]
As you can see below, Settings button is missing.

![image](https://user-images.githubusercontent.com/11430080/172067036-543ce193-3e38-47fd-93e4-1a3c2749a9d1.png)

I even removed some of the buttons and still Settings doesn't show up.

I am using version 19 on Pop!_OS with GNOME 42 and it may not work with the System76 extensions that customize GNOME for Pop!_OS.

**Comment by pratap-panabaka** [comment]
Hi..
Version 19 on Pop!_OS and System76 are both one OS??
If I want to test this, can you provide the link for OS.. I have to download install and see it.

**Comment by jfftck** [comment]
It is the version of Pop!_OS that is on System76's website (https://pop.system76.com/).

**Comment by Hannibal83dk** [comment]
Hey..thanks for a great extension.

I have the same issue, only I am also missing switch user and orientation. I don't really need those last two though. 

![image](https://user-images.githubusercontent.com/88366778/185719744-10e7af0b-7ae6-417a-b6df-0e7626a73fbe.png)

Operating System: Ubuntu 22.04.1 LTS              
          Kernel: Linux 5.15.0-46-generic
    Architecture: x86-64
Windowing System: X11

**Comment by pratap-panabaka** [comment]
Hi can we have a zoom call to discuss about this when you have free time?

thanks

**Comment by Hannibal83dk** [comment]
Hey PRATAP

Ok did not expect this much engagement but i guess yes. I am able to talk the next hour or so, otherwise maybe tomorrow or during the week.

I am not sure which time zone you are in, im in +2 GMT and could probably be available sometime after 12 noon tomorrow??

Kind regards

**Comment by pratap-panabaka** [comment]
Hi, I am from India,
India Standard Time
Time zone in India (GMT+5:30)

• 12:00 PM ( 12:00 ) GMT+2  =  3:30 PM (15:30) India Time

I am available between 12 PM to 2 PM GMT+2.

**Comment by Hannibal83dk** [comment]
Ok cool lets do it at 12 PM then?? 

I will send you an email with contacts

**Comment by Hannibal83dk** [comment]
Actually I have a meeting endig at 12 could we say 12:30?

**Comment by pratap-panabaka** [comment]
Ok Sure, No worries. I am waiting for your call. Thank You.

**Comment by Hannibal83dk** [comment]
Patrick Petersen is inviting you to a scheduled Zoom meeting.


Topic: Patrick Petersen's Personal Meeting Room


Join Zoom Meeting

https://us05web.zoom.us/j/9854222782?pwd=UmtJWE1hUXNsS1diVkEzUnV1SGNNQT09


Meeting ID: 985 422 2782

Passcode: YRZ74M

Den man. 22. aug. 2022 kl. 11.59 skrev PRATAP PANABAKA <
***@***.***>:

**Comment by pratap-panabaka** [comment]
Hi Mr. Patrick, I think in version 42.2 they have changed some code, can you open `extension.js` file and look for line numbers 223 to 226

````
        // SETTINGS BUTTON

	let app = this._settingsApp = SHELL_MAJOR_VERSION >=42 ? Shell.AppSystem.get_default().lookup_app('org.gnome.Settings.desktop') :
									Shell.AppSystem.get_default().lookup_app('gnome-control-center.desktop');
````

after editing the portion should look like the below:
````
        // SETTINGS BUTTON

	let app = this._settingsApp = Shell.AppSystem.get_default().lookup_app('gnome-control-center.desktop');
        if (app) {	
        this._settingsButton = this._createActionButton('org.gnome.Settings-symbolic', _('Settings'));
        this._settingsButton.connect('clicked', () => {
                        				Main.overview.hide();
                					this._settingsApp.activate();
                				      				     });
````

**Comment by pratap-panabaka** [comment]
![Screenshot](https://user-images.githubusercontent.com/40719899/185908987-c3ff7cf6-ae79-4dc2-a49b-fa3c5bfde1b1.png)

**Comment by pratap-panabaka** [comment]
This should work from `extension.js` file

````
        // SETTINGS BUTTON

	let app = this._settingsApp = Shell.AppSystem.get_default().lookup_app('gnome-control-center.desktop');
        if (app) {	
        this._settingsButton = this._createActionButton('org.gnome.Settings-symbolic', _('Settings'));
        this._settingsButton.connect('clicked', () => {
                        				Main.overview.hide();
                					this._settingsApp.activate();
                				      				     });
             				      				     
        item.actor.add(this._settingsButton);
   	} else {
            log('Missing required core component Settings, expect trouble…');
            this._settingsButton = null;
        } 
       
        //  LOCK BUTTON
````

**Comment by pratap-panabaka** [comment]
Settings Icon is back. We are done.
Can you provide me the output for this command `cat /etc/passwd | grep /home` to dig about the switch user icon button?

Example: 
````
pratap@ANTARCTICA:~$ cat /etc/passwd | grep /home
syslog:x:104:111::/home/syslog:/usr/sbin/nologin
cups-pk-helper:x:115:122:user for cups-pk-helper service,,,:/home/cups-pk-helper:/usr/sbin/nologin
pratap:x:1000:1000:PRATAP,,,:/home/pratap:/bin/bash
yugan:x:1001:1001:YUGAN,,,:/home/yugan:/bin/bash
pratap@ANTARCTICA:~$ 
````

**Comment by pratap-panabaka** [comment]
I have submitted the version 20 for code review and it got approved just now. Once you restart gnome-shell, the version should change to 20 and it should work for settings button. Plz check.

**Comment by Hannibal83dk** [comment]
![image](https://user-images.githubusercontent.com/88366778/185923628-605bc3b6-89ba-495a-955c-9f740aea138f.png)


Awsome, thanks a lot Pratap.

Really appreciate your effort

**Comment by Hannibal83dk** [comment]
patrick@patrick-Lenovo:~$ cat /etc/passwd | grep /home
syslog:x:104:111::/home/syslog:/usr/sbin/nologin
cups-pk-helper:x:115:122:user for cups-pk-helper service,,,:/home/cups-pk-helper:/usr/sbin/nologin
patrick:x:1000:1000:Patrick Petersen,,,:/home/patrick:/bin/bash
patrick@patrick-Lenovo:~$

**Comment by Hannibal83dk** [comment]
````
patrick@patrick-Lenovo:~$ cat /etc/passwd | grep /home
syslog:x:104:111::/home/syslog:/usr/sbin/nologin
cups-pk-helper:x:115:122:user for cups-pk-helper service,,,:/home/cups-pk-helper:/usr/sbin/nologin
patrick:x:1000:1000:Patrick Petersen,,,:/home/patrick:/bin/bash
patrick@patrick-Lenovo:~$ 
````

**Comment by pratap-panabaka** [comment]
You don’t have a switch-user icon rite so no need to look for available users in the system with the above digging. Or am I wrong??

![image](https://user-images.githubusercontent.com/40719899/185929557-1b19ddee-1c93-443c-8b77-8c846c6c9b3e.png)

a switch-user icon is not showing rite, or I am wrong?

**Comment by pratap-panabaka** [comment]
> It is the version of Pop!_OS that is on System76's website (https://pop.system76.com/).

@jfftck can you check now for the settings icon, please? I am sorry for not being able to install pop Os by the time you raised this issue. Extremely sorry about that.

**Comment by Hannibal83dk** [comment]
that's right I could later create a new dummy account to see if it shows up??

**Comment by pratap-panabaka** [comment]
That’s cool. If you can confirm about switch user icon I will close this issue. Take your time to test it. Until then bye.

**Comment by Hannibal83dk** [comment]
![image](https://user-images.githubusercontent.com/88366778/185944419-cfbbd1f5-4215-4b6c-80ed-0b2d0722028d.png)

It works! :)

**Comment by pratap-panabaka** [comment]
Thanks for your confirmation and support. Thank you very much.
